### ISSUE TITLE
! Undefined control sequence. <write> \pp@spagectr{sidenote}{1}{\pp@g@sidenote  }{\thepage }

### ISSUE THREAD

**Issue by aussetg** [cgnieder/snotez#2] opened 2021-06-21 09:25 UTC
On TeXLive 2021, I get 

```latex
! Undefined control sequence.
<write> \pp@spagectr{sidenote}{1}{\pp@g@sidenote 
                                         }{\thepage }
```

unless I add `\newcommand{\pp@g@sidenote}{}` to the preamble.

No idea why.

**Comment by cgnieder** [comment] 2022-01-05 13:43
I cannot reproduce the issue. The following runs just fine:
```latex
\documentclass{article}
\usepackage{snotez}
\setsidenotes{perpage=true}
\begin{document}

Text\sidenote{Text}
\newpage
Text\sidenote{Text}

\end{document}
```

**Comment by manoelmozzer** [comment] 2022-02-10 00:13
I reproduce the issue with the book class:
```latex
\documentclass{book}
\usepackage{snotez}

\begin{document}

\chapter{Chapter 1}
Text\sidenote{Text}

\end{document}
````

If insert ``\counterwithout{sidenote}{chapter}`` or the [aussetg's answer](https://github.com/cgnieder/snotez/issues/2#issue-926016878) in the preambule, the issue not happen. But, this not reset the number of sidenote after each chapter.

An alternative is use the `titlesec` package and force the counter reset after the chapter code:
```latex
\usepackage{titlesec}
\titleformat{\chapter}[display]% Standard chapter
        {\normalfont\huge\bfseries}{\chaptertitlename\ \thechapter}{20pt}{\Huge}
        [\setcounter{sidenote}{0}]% Reset counter after chapter code
```

@cgnieder any idea how to fix this in the core of snotez package?

**Comment by manoelmozzer** [comment] 2022-02-10 00:15
Funny thing, this compile without the error:

```latex
\documentclass{book}
\usepackage{snotez}

\begin{document}

Text\sidenote{Text}

\chapter{Chapter 1}
Text\sidenote{Text}

\end{document}
```

But, the index of the second sidenote (after the chapter) is 3, instead 2.

**Comment by cgnieder** [comment] 2022-02-10 17:54
Interesting…

**Comment by cgnieder** [comment] 2022-02-10 18:17
I think this is a bug in the `perpage` package:

```latex
\documentclass{book}
\usepackage{perpage}
\newcounter{foo}[chapter]
\MakeSorted{foo}
\begin{document}

\chapter{Text}
\stepcounter{foo}\thefoo

\end{document}
```

But

- I think it is not really needed to do `\MakeSorted{sidenote}` and
- there also is `zref-perpage`

so this should easily be fixed in `snotez`.

**Closed as completed** 2022-02-10 18:18 UTC
